services:
  mongo:
    image: mongo:latest
    container_name: mongo-shard1
    restart: always
    command: ["--replSet", "shard1", "--bind_ip_all", "--shardsvr", "--port", "27017"]
    #extra_hosts:
    #  - "host.docker.internal:host-gateway"
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - mongo

volumes:
  mongo_data:
    driver: local
networks:
  mongo:
    external: true

