services:
  mongo:
    image: mongo:latest
    container_name: mongo-shard1
    restart: always
    command: ["--replSet", "rs1", "--bind_ip_all", "--port", "27017"]
    #extra_hosts:
    #  - "host.docker.internal:host-gateway"
    ports:
      - "27018:27018"
    volumes:
      - mongo_data:/data/db
      - "./config/mongod.conf.orig:/etc/mongod.conf.orig"
volumes:
  mongo_data:
    driver: local
