services:
  mongo_config:
    image: mongo
    command: ["--replSet", "config", "--configsvr", "--bind_ip_all", "--port", "27017"]
    ports:
      - 27017:27017
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - "mongo_config:/data/configdb"
    networks:
      - mongo

volumes:
  mongo_config:

networks:
  mongo:
    external: true
