services:
  mongo_config:
    image: mongo
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    ports:
      - 27017:27017
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - "mongo_data:/data/db"
      - "mongo_config:/data/configdb"
      - "./config/mongod.conf.orig:/etc/mongod.conf.orig"

volumes:
  mongo_data:
  mongo_config:
