services:
  mongo_router:
    image: mongo:latest
    container_name: mongo-router
    restart: always
    ports:
      - "27020:27017"
    networks:
      - mongo

volumes:
  mongo_data:
    driver: local
networks:
  mongo:
    external: true

