services:
  mongo_router:
    image: mongo:latest
    container_name: mongo-router
    restart: always
    ports:
      - "27020:27017"
    volumes:
      - "./config/mongod.conf.orig:/etc/mongod.conf.orig"
    networks:
      - mongo

volumes:
  mongo_data:
    driver: local
networks:
  mongo:
    external: true

