services:
  mongo:
    image: mongo:latest
    container_name: mongo-shard2
    restart: always
    command: ["--replSet", "rs2", "--bind_ip_all"]
    #extra_hosts:
    #  - "host.docker.internal:host-gateway"
    ports:
      - "27019:27017"
    volumes:
      - mongo_data:/data/db
      - "./config/mongod.conf.orig:/etc/mongod.conf.orig"
    networks:
      - mongo

volumes:
  mongo_data:
    driver: local
networks:
  mongo:
    external: true

