services:
  mongo:
    image: mongo:latest
    container_name: mongo-shard2
    restart: always
    ports:
      - "27019:27019"
    volumes:
      - mongo_data:/data/db
      - "./config/mongod.conf.orig:/etc/mongod.conf.orig"
volumes:
  mongo_data:
    driver: local
